# Site settings
title: Automate Green
email: brandon@automategreen.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.automategreen.com" # the base hostname & protocol for your site
excerpt_separator: <!--more-->
# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["with_toc_data"]
exclude:
  - "vendor"
  - "bower_components"
  - "bower.json"
  - "README.md"
  - "Gemfile*"
  - "LICENSE"
  - "gruntfile.js"
  - "package.json"
  - "tag-gen.sh"
  - "s3_website.yml"

permalink: pretty

tag_page_layout: tag_page
tag_page_dir: tag

assets:
  js_compressor:  uglifier
  css_compressor: sass

gems:
  - jekyll-sitemap